output_text = []
output_text.append("Hello from Python!")
output_text.append("This output is generated by Jenkins.")
output_text.append("Calculating sum of numbers from 1 to 5...")

total = sum(range(1, 6))
output_text.append(f"Result: {total}")

# Write text output
with open("output.txt", "w") as txt_file:
    for line in output_text:
        txt_file.write(line + "\n")

# Write HTML output
html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Jenkins Python Output</title>
</head>
<body>
    <h1>Jenkins Job Result</h1>
    <p>Hello from Python!</p>
    <p>Sum of numbers from 1 to 5: <b>{total}</b></p>
</body>
</html>
"""

with open("output.html", "w") as html_file:
    html_file.write(html_content)

print("Output files generated: output.txt, output.html")
